### ISSUE TITLE
TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by acmeonce** [bazwilliams/upnp-playlist-service#13]
Hi

When trying to add a new (sleep) schedule I get the following error in `/var/log/nodejs/ds-service.log`:

```
2015-12-14T03:23:36.110Z - info: ::1 POST /api/devices/<uuid>/schedules 500 0.478

TypeError: Cannot read property 'push' of undefined
    at addValidSchedule (/opt/upnp-playlist-service/server/schedulemanager.js:94:29)
    at Object.exports.getItem (/opt/upnp-playlist-service/node_modules/node-persist/node-persist.js:288:9)
    at Object.addSchedule (/opt/upnp-playlist-service/server/schedulemanager.js:74:17)
    at exports.addSchedule (/opt/upnp-playlist-service/server/routes/schedule.js:32:29)
    at Layer.handle [as handle_request] (/opt/upnp-playlist-service/node_modules/express/lib/router/layer.js:82:5)
    at next (/opt/upnp-playlist-service/node_modules/express/lib/router/route.js:100:13)
    at Route.dispatch (/opt/upnp-playlist-service/node_modules/express/lib/router/route.js:81:3)
    at Layer.handle [as handle_request] (/opt/upnp-playlist-service/node_modules/express/lib/router/layer.js:82:5)
    at /opt/upnp-playlist-service/node_modules/express/lib/router/index.js:233:24
    at param (/opt/upnp-playlist-service/node_modules/express/lib/router/index.js:330:14)
```

Any idea?

Thanks & best regards

**Comment by bazwilliams** [comment]
Can you send me your actions.json file?

**Comment by acmeonce** [comment]
On 14/12/15 13:43, Barry John Williams wrote:

> Can you send me your actions.json file?

./node_modules/bower/node_modules/configstore/node_modules/js-yaml/node_modules/argparse/lib/action.js?

**Comment by bazwilliams** [comment]
No. There should be one under the persist folder

**Comment by acmeonce** [comment]
There isn't any file under the persist folder. Permissions (nodejs:nodejs) seem to be correct.

**Comment by bazwilliams** [comment]
Looks like there is a bug - can you create an actions.js file as follows:

`cat [] > persist/actions.json`

Ensure it as the correct perms `nodejs:nodejs` and restart the app?

**Comment by bazwilliams** [comment]
Looks like a potential race condition when application starts without any existing `actions.json` file.

**Comment by acmeonce** [comment]
That did the trick! I'm now able to add schedule entries. Many thanks!

**Comment by bazwilliams** [comment]
Glad to hear it! Thanks for reporting the bug!
